name: auto_securo_user
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  pin_code_fields: ^7.0.0
  fancy_bottom_navigation: ^0.3.3

  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  page_transition: ^1.1.7+6
  cached_network_image: ^3.0.0
  image_picker: ^0.7.4
  firebase_storage: ^8.0.1
  date_format: ^2.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
